/** Declaration file generated by dts-gen */

declare module "custom-env";

// export function config(...args: any[]): any;

// export function dotenvConfig(...args: any[]): any;

// export function env(...args: any[]): any;

