/** Declaration file generated by dts-gen */

declare module "njwt";

// export class Jwt {
//     constructor(claims: any, enforceDefaultFields: any);

//     compact(): any;

//     isExpired(): any;

//     isNotBefore(): any;

//     isSupportedAlg(alg: any): any;

//     setClaim(claim: any, value: any): any;

//     setExpiration(exp: any): any;

//     setHeader(param: any, value: any): any;

//     setIssuedAt(iat: any): any;

//     setIssuer(iss: any): any;

//     setJti(jti: any): any;

//     setNotBefore(nbf: any): any;

//     setSigningAlgorithm(alg: any): any;

//     setSigningKey(key: any): any;

//     setSubject(sub: any): any;

//     sign(payload: any, algorithm: any, cryptoInput: any): any;

//     toString(): any;

// }

// export class JwtBody {
//     constructor(claims: any);

//     compact(): any;

//     toJSON(): any;

// }

// export class JwtHeader {
//     constructor(header: any);

//     compact(): any;

// }

// export class Verifier {
//     constructor();

//     isSupportedAlg(alg: any): any;

//     setKeyResolver(keyResolver: any): void;

//     setSigningAlgorithm(alg: any): any;

//     setSigningKey(keyStr: any): any;

//     verify(jwtString: any, cb: any): any;

//     withKeyResolver(keyResolver: any): any;

// }

// export function base64urlEncode(data: any): any;

// export function base64urlUnescape(str: any): any;

// export function create(claims: any, secret: any, alg: any, ...args: any[]): any;

// export function createVerifier(): any;

// export function verify(...args: any[]): any;