on:
  push:
    branches: ["develop"]
  
  pull_request:
    branches: ["develop"]

  release:
    types: [created]

name: Deploy to Amazon ECS

jobs:
  test:
     name: Test
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Install project dependencies
       run: |
          npm install
       
     - name: Run tests
       run: |
          sudo npm run test


  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: '.' # set the path to the folder wher the Dokerfile is located
          options: '-t mono-soc-app-dev' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web