on:
  push:
    branches: ["develop"]
  
  pull_request:
    branches: ["develop"]

  release:
    types: [created]

name: Deploy to Amazon ECS

jobs:
  test:
     name: Test
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Install project dependencies
       run: |
          npm install
       
     - name: Run tests
       run: |
          sudo npm run test


  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true