/** Declaration file generated by dts-gen */

declare module "secure-random";

// export = secure_random;

declare function secure_random(count: any, options: any): any;

declare namespace secure_random {
    function randomArray(byteCount: any): any;

    function randomBuffer(byteCount: any): any;

    function randomUint8Array(byteCount: any): any;

}

